### PR TITLE
Pr/6/sourceimport

### PR DESCRIPTION
**Pull request by mojoaxel**

### CODE REVIEW

**Comment by mojoaxel** [comment]
This fixes the problems with https://github.com/visjs/vis-charts/pull/6
I'm not sure if this is the right solution, but it seam to work.

_(Branch needs to re rebased from vis-charts/master)_

**Comment by mojoaxel** [comment]
@Thomaash What do you think about that?

**Comment by Thomaash** [comment]
Oh, I forgot about this. I tried to make it work but it didn't work for me.

**Comment by Thomaash** [comment]
Main issue is that rollup-plugin-typescript doesn't work with type reexporting (which is used in some of the projects).

**Comment by Thomaash** [comment]
I solved it using the same method but different plugins.

**Comment by Thomaash** [comment]
Also what is rollup-plugin-node-builtins for?

**Comment by mojoaxel** [comment]
> Also what is rollup-plugin-node-builtins for?

I can't remember

**Pull request closed without merging**
